{
                  # My giga scuffed standard library LULE #
                  
                  _:;x;{x} # identity function since we can't use parenthesis in expressions #
                  
                  printDigit: ;print num; print(48+num)
              
                  newline: ;print; print(10)
                  
                  # stdlib end #
              
                  newline(print)
                  print(48 + 7)
                  newline(print)
              }